// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: battlesnake_env.proto

package envpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BattlesnakeEnv_Configure_FullMethodName = "/battlesnake_env.BattlesnakeEnv/Configure"
	BattlesnakeEnv_Reset_FullMethodName     = "/battlesnake_env.BattlesnakeEnv/Reset"
	BattlesnakeEnv_Step_FullMethodName      = "/battlesnake_env.BattlesnakeEnv/Step"
)

// BattlesnakeEnvClient is the client API for BattlesnakeEnv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BattlesnakeEnvClient interface {
	// Configure sets up the environment parameters.
	Configure(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	// Reset resets specified environments and returns observations.
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*Observations, error)
	// Step takes actions in specified environments and returns results.
	Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepResponse, error)
}

type battlesnakeEnvClient struct {
	cc grpc.ClientConnInterface
}

func NewBattlesnakeEnvClient(cc grpc.ClientConnInterface) BattlesnakeEnvClient {
	return &battlesnakeEnvClient{cc}
}

func (c *battlesnakeEnvClient) Configure(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, BattlesnakeEnv_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battlesnakeEnvClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*Observations, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Observations)
	err := c.cc.Invoke(ctx, BattlesnakeEnv_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battlesnakeEnvClient) Step(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StepResponse)
	err := c.cc.Invoke(ctx, BattlesnakeEnv_Step_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BattlesnakeEnvServer is the server API for BattlesnakeEnv service.
// All implementations must embed UnimplementedBattlesnakeEnvServer
// for forward compatibility.
type BattlesnakeEnvServer interface {
	// Configure sets up the environment parameters.
	Configure(context.Context, *ConfigRequest) (*ConfigResponse, error)
	// Reset resets specified environments and returns observations.
	Reset(context.Context, *ResetRequest) (*Observations, error)
	// Step takes actions in specified environments and returns results.
	Step(context.Context, *StepRequest) (*StepResponse, error)
	mustEmbedUnimplementedBattlesnakeEnvServer()
}

// UnimplementedBattlesnakeEnvServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBattlesnakeEnvServer struct{}

func (UnimplementedBattlesnakeEnvServer) Configure(context.Context, *ConfigRequest) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedBattlesnakeEnvServer) Reset(context.Context, *ResetRequest) (*Observations, error) {
	return nil, status.Error(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedBattlesnakeEnvServer) Step(context.Context, *StepRequest) (*StepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Step not implemented")
}
func (UnimplementedBattlesnakeEnvServer) mustEmbedUnimplementedBattlesnakeEnvServer() {}
func (UnimplementedBattlesnakeEnvServer) testEmbeddedByValue()                        {}

// UnsafeBattlesnakeEnvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BattlesnakeEnvServer will
// result in compilation errors.
type UnsafeBattlesnakeEnvServer interface {
	mustEmbedUnimplementedBattlesnakeEnvServer()
}

func RegisterBattlesnakeEnvServer(s grpc.ServiceRegistrar, srv BattlesnakeEnvServer) {
	// If the following call panics, it indicates UnimplementedBattlesnakeEnvServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BattlesnakeEnv_ServiceDesc, srv)
}

func _BattlesnakeEnv_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattlesnakeEnvServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattlesnakeEnv_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattlesnakeEnvServer).Configure(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattlesnakeEnv_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattlesnakeEnvServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattlesnakeEnv_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattlesnakeEnvServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattlesnakeEnv_Step_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattlesnakeEnvServer).Step(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattlesnakeEnv_Step_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattlesnakeEnvServer).Step(ctx, req.(*StepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BattlesnakeEnv_ServiceDesc is the grpc.ServiceDesc for BattlesnakeEnv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BattlesnakeEnv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "battlesnake_env.BattlesnakeEnv",
	HandlerType: (*BattlesnakeEnvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Configure",
			Handler:    _BattlesnakeEnv_Configure_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _BattlesnakeEnv_Reset_Handler,
		},
		{
			MethodName: "Step",
			Handler:    _BattlesnakeEnv_Step_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "battlesnake_env.proto",
}
