// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: battlesnake_env.proto

package envpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumEnvs       int32                  `protobuf:"varint,1,opt,name=num_envs,json=numEnvs,proto3" json:"num_envs,omitempty"`
	BoardWidth    int32                  `protobuf:"varint,2,opt,name=board_width,json=boardWidth,proto3" json:"board_width,omitempty"`
	BoardHeight   int32                  `protobuf:"varint,3,opt,name=board_height,json=boardHeight,proto3" json:"board_height,omitempty"`
	OpponentType  string                 `protobuf:"bytes,4,opt,name=opponent_type,json=opponentType,proto3" json:"opponent_type,omitempty"` // "none", "random", "brs"
	MaxTurns      int32                  `protobuf:"varint,5,opt,name=max_turns,json=maxTurns,proto3" json:"max_turns,omitempty"`            // 0 = default (500)
	BrsBudgetMs   int32                  `protobuf:"varint,6,opt,name=brs_budget_ms,json=brsBudgetMs,proto3" json:"brs_budget_ms,omitempty"` // BRS budget in ms (default 50)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_battlesnake_env_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battlesnake_env_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_battlesnake_env_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigRequest) GetNumEnvs() int32 {
	if x != nil {
		return x.NumEnvs
	}
	return 0
}

func (x *ConfigRequest) GetBoardWidth() int32 {
	if x != nil {
		return x.BoardWidth
	}
	return 0
}

func (x *ConfigRequest) GetBoardHeight() int32 {
	if x != nil {
		return x.BoardHeight
	}
	return 0
}

func (x *ConfigRequest) GetOpponentType() string {
	if x != nil {
		return x.OpponentType
	}
	return ""
}

func (x *ConfigRequest) GetMaxTurns() int32 {
	if x != nil {
		return x.MaxTurns
	}
	return 0
}

func (x *ConfigRequest) GetBrsBudgetMs() int32 {
	if x != nil {
		return x.BrsBudgetMs
	}
	return 0
}

type ConfigResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NumEnvs         int32                  `protobuf:"varint,1,opt,name=num_envs,json=numEnvs,proto3" json:"num_envs,omitempty"`
	SpatialChannels int32                  `protobuf:"varint,2,opt,name=spatial_channels,json=spatialChannels,proto3" json:"spatial_channels,omitempty"` // 11
	SpatialSize     int32                  `protobuf:"varint,3,opt,name=spatial_size,json=spatialSize,proto3" json:"spatial_size,omitempty"`             // 21
	NumScalars      int32                  `protobuf:"varint,4,opt,name=num_scalars,json=numScalars,proto3" json:"num_scalars,omitempty"`                // 8
	NumActions      int32                  `protobuf:"varint,5,opt,name=num_actions,json=numActions,proto3" json:"num_actions,omitempty"`                // 4
	ShmPath         string                 `protobuf:"bytes,6,opt,name=shm_path,json=shmPath,proto3" json:"shm_path,omitempty"`                          // shared memory file path (empty = not using mmap)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_battlesnake_env_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battlesnake_env_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_battlesnake_env_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigResponse) GetNumEnvs() int32 {
	if x != nil {
		return x.NumEnvs
	}
	return 0
}

func (x *ConfigResponse) GetSpatialChannels() int32 {
	if x != nil {
		return x.SpatialChannels
	}
	return 0
}

func (x *ConfigResponse) GetSpatialSize() int32 {
	if x != nil {
		return x.SpatialSize
	}
	return 0
}

func (x *ConfigResponse) GetNumScalars() int32 {
	if x != nil {
		return x.NumScalars
	}
	return 0
}

func (x *ConfigResponse) GetNumActions() int32 {
	if x != nil {
		return x.NumActions
	}
	return 0
}

func (x *ConfigResponse) GetShmPath() string {
	if x != nil {
		return x.ShmPath
	}
	return ""
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvIds        []int32                `protobuf:"varint,1,rep,packed,name=env_ids,json=envIds,proto3" json:"env_ids,omitempty"` // empty = reset all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_battlesnake_env_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battlesnake_env_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_battlesnake_env_proto_rawDescGZIP(), []int{2}
}

func (x *ResetRequest) GetEnvIds() []int32 {
	if x != nil {
		return x.EnvIds
	}
	return nil
}

type Observations struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Flat float32 arrays, one per env.
	// spatial: [num_envs * channels * size * size]
	Spatial []float32 `protobuf:"fixed32,1,rep,packed,name=spatial,proto3" json:"spatial,omitempty"`
	// scalars: [num_envs * num_scalars]
	Scalars []float32 `protobuf:"fixed32,2,rep,packed,name=scalars,proto3" json:"scalars,omitempty"`
	// action_mask: [num_envs * 4] (true = valid action)
	ActionMask    []bool  `protobuf:"varint,3,rep,packed,name=action_mask,json=actionMask,proto3" json:"action_mask,omitempty"`
	EnvIds        []int32 `protobuf:"varint,4,rep,packed,name=env_ids,json=envIds,proto3" json:"env_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observations) Reset() {
	*x = Observations{}
	mi := &file_battlesnake_env_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observations) ProtoMessage() {}

func (x *Observations) ProtoReflect() protoreflect.Message {
	mi := &file_battlesnake_env_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observations.ProtoReflect.Descriptor instead.
func (*Observations) Descriptor() ([]byte, []int) {
	return file_battlesnake_env_proto_rawDescGZIP(), []int{3}
}

func (x *Observations) GetSpatial() []float32 {
	if x != nil {
		return x.Spatial
	}
	return nil
}

func (x *Observations) GetScalars() []float32 {
	if x != nil {
		return x.Scalars
	}
	return nil
}

func (x *Observations) GetActionMask() []bool {
	if x != nil {
		return x.ActionMask
	}
	return nil
}

func (x *Observations) GetEnvIds() []int32 {
	if x != nil {
		return x.EnvIds
	}
	return nil
}

type StepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvIds        []int32                `protobuf:"varint,1,rep,packed,name=env_ids,json=envIds,proto3" json:"env_ids,omitempty"`
	Actions       []int32                `protobuf:"varint,2,rep,packed,name=actions,proto3" json:"actions,omitempty"` // 0=Up, 1=Down, 2=Left, 3=Right
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepRequest) Reset() {
	*x = StepRequest{}
	mi := &file_battlesnake_env_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepRequest) ProtoMessage() {}

func (x *StepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battlesnake_env_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepRequest.ProtoReflect.Descriptor instead.
func (*StepRequest) Descriptor() ([]byte, []int) {
	return file_battlesnake_env_proto_rawDescGZIP(), []int{4}
}

func (x *StepRequest) GetEnvIds() []int32 {
	if x != nil {
		return x.EnvIds
	}
	return nil
}

func (x *StepRequest) GetActions() []int32 {
	if x != nil {
		return x.Actions
	}
	return nil
}

type StepResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Observations *Observations          `protobuf:"bytes,1,opt,name=observations,proto3" json:"observations,omitempty"`
	Rewards      []float32              `protobuf:"fixed32,2,rep,packed,name=rewards,proto3" json:"rewards,omitempty"`
	Dones        []bool                 `protobuf:"varint,3,rep,packed,name=dones,proto3" json:"dones,omitempty"`
	// Info per env (JSON-encoded for flexibility).
	Infos         []string `protobuf:"bytes,4,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResponse) Reset() {
	*x = StepResponse{}
	mi := &file_battlesnake_env_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResponse) ProtoMessage() {}

func (x *StepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battlesnake_env_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResponse.ProtoReflect.Descriptor instead.
func (*StepResponse) Descriptor() ([]byte, []int) {
	return file_battlesnake_env_proto_rawDescGZIP(), []int{5}
}

func (x *StepResponse) GetObservations() *Observations {
	if x != nil {
		return x.Observations
	}
	return nil
}

func (x *StepResponse) GetRewards() []float32 {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *StepResponse) GetDones() []bool {
	if x != nil {
		return x.Dones
	}
	return nil
}

func (x *StepResponse) GetInfos() []string {
	if x != nil {
		return x.Infos
	}
	return nil
}

type StepSignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        uint64                 `protobuf:"varint,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepSignalRequest) Reset() {
	*x = StepSignalRequest{}
	mi := &file_battlesnake_env_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepSignalRequest) ProtoMessage() {}

func (x *StepSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battlesnake_env_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepSignalRequest.ProtoReflect.Descriptor instead.
func (*StepSignalRequest) Descriptor() ([]byte, []int) {
	return file_battlesnake_env_proto_rawDescGZIP(), []int{6}
}

func (x *StepSignalRequest) GetStepId() uint64 {
	if x != nil {
		return x.StepId
	}
	return 0
}

type StepSignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        uint64                 `protobuf:"varint,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepSignalResponse) Reset() {
	*x = StepSignalResponse{}
	mi := &file_battlesnake_env_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepSignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepSignalResponse) ProtoMessage() {}

func (x *StepSignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battlesnake_env_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepSignalResponse.ProtoReflect.Descriptor instead.
func (*StepSignalResponse) Descriptor() ([]byte, []int) {
	return file_battlesnake_env_proto_rawDescGZIP(), []int{7}
}

func (x *StepSignalResponse) GetStepId() uint64 {
	if x != nil {
		return x.StepId
	}
	return 0
}

var File_battlesnake_env_proto protoreflect.FileDescriptor

const file_battlesnake_env_proto_rawDesc = "" +
	"\n" +
	"\x15battlesnake_env.proto\x12\x0fbattlesnake_env\"\xd4\x01\n" +
	"\rConfigRequest\x12\x19\n" +
	"\bnum_envs\x18\x01 \x01(\x05R\anumEnvs\x12\x1f\n" +
	"\vboard_width\x18\x02 \x01(\x05R\n" +
	"boardWidth\x12!\n" +
	"\fboard_height\x18\x03 \x01(\x05R\vboardHeight\x12#\n" +
	"\ropponent_type\x18\x04 \x01(\tR\fopponentType\x12\x1b\n" +
	"\tmax_turns\x18\x05 \x01(\x05R\bmaxTurns\x12\"\n" +
	"\rbrs_budget_ms\x18\x06 \x01(\x05R\vbrsBudgetMs\"\xd6\x01\n" +
	"\x0eConfigResponse\x12\x19\n" +
	"\bnum_envs\x18\x01 \x01(\x05R\anumEnvs\x12)\n" +
	"\x10spatial_channels\x18\x02 \x01(\x05R\x0fspatialChannels\x12!\n" +
	"\fspatial_size\x18\x03 \x01(\x05R\vspatialSize\x12\x1f\n" +
	"\vnum_scalars\x18\x04 \x01(\x05R\n" +
	"numScalars\x12\x1f\n" +
	"\vnum_actions\x18\x05 \x01(\x05R\n" +
	"numActions\x12\x19\n" +
	"\bshm_path\x18\x06 \x01(\tR\ashmPath\"'\n" +
	"\fResetRequest\x12\x17\n" +
	"\aenv_ids\x18\x01 \x03(\x05R\x06envIds\"\x8c\x01\n" +
	"\fObservations\x12\x1c\n" +
	"\aspatial\x18\x01 \x03(\x02B\x02\x10\x01R\aspatial\x12\x1c\n" +
	"\ascalars\x18\x02 \x03(\x02B\x02\x10\x01R\ascalars\x12#\n" +
	"\vaction_mask\x18\x03 \x03(\bB\x02\x10\x01R\n" +
	"actionMask\x12\x1b\n" +
	"\aenv_ids\x18\x04 \x03(\x05B\x02\x10\x01R\x06envIds\"H\n" +
	"\vStepRequest\x12\x1b\n" +
	"\aenv_ids\x18\x01 \x03(\x05B\x02\x10\x01R\x06envIds\x12\x1c\n" +
	"\aactions\x18\x02 \x03(\x05B\x02\x10\x01R\aactions\"\x9f\x01\n" +
	"\fStepResponse\x12A\n" +
	"\fobservations\x18\x01 \x01(\v2\x1d.battlesnake_env.ObservationsR\fobservations\x12\x1c\n" +
	"\arewards\x18\x02 \x03(\x02B\x02\x10\x01R\arewards\x12\x18\n" +
	"\x05dones\x18\x03 \x03(\bB\x02\x10\x01R\x05dones\x12\x14\n" +
	"\x05infos\x18\x04 \x03(\tR\x05infos\",\n" +
	"\x11StepSignalRequest\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\x04R\x06stepId\"-\n" +
	"\x12StepSignalResponse\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\x04R\x06stepId2\xc1\x02\n" +
	"\x0eBattlesnakeEnv\x12L\n" +
	"\tConfigure\x12\x1e.battlesnake_env.ConfigRequest\x1a\x1f.battlesnake_env.ConfigResponse\x12E\n" +
	"\x05Reset\x12\x1d.battlesnake_env.ResetRequest\x1a\x1d.battlesnake_env.Observations\x12C\n" +
	"\x04Step\x12\x1c.battlesnake_env.StepRequest\x1a\x1d.battlesnake_env.StepResponse\x12U\n" +
	"\n" +
	"StepSignal\x12\".battlesnake_env.StepSignalRequest\x1a#.battlesnake_env.StepSignalResponseB*Z(github.com/bodist/haruko/cmd/rlenv/envpbb\x06proto3"

var (
	file_battlesnake_env_proto_rawDescOnce sync.Once
	file_battlesnake_env_proto_rawDescData []byte
)

func file_battlesnake_env_proto_rawDescGZIP() []byte {
	file_battlesnake_env_proto_rawDescOnce.Do(func() {
		file_battlesnake_env_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_battlesnake_env_proto_rawDesc), len(file_battlesnake_env_proto_rawDesc)))
	})
	return file_battlesnake_env_proto_rawDescData
}

var file_battlesnake_env_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_battlesnake_env_proto_goTypes = []any{
	(*ConfigRequest)(nil),      // 0: battlesnake_env.ConfigRequest
	(*ConfigResponse)(nil),     // 1: battlesnake_env.ConfigResponse
	(*ResetRequest)(nil),       // 2: battlesnake_env.ResetRequest
	(*Observations)(nil),       // 3: battlesnake_env.Observations
	(*StepRequest)(nil),        // 4: battlesnake_env.StepRequest
	(*StepResponse)(nil),       // 5: battlesnake_env.StepResponse
	(*StepSignalRequest)(nil),  // 6: battlesnake_env.StepSignalRequest
	(*StepSignalResponse)(nil), // 7: battlesnake_env.StepSignalResponse
}
var file_battlesnake_env_proto_depIdxs = []int32{
	3, // 0: battlesnake_env.StepResponse.observations:type_name -> battlesnake_env.Observations
	0, // 1: battlesnake_env.BattlesnakeEnv.Configure:input_type -> battlesnake_env.ConfigRequest
	2, // 2: battlesnake_env.BattlesnakeEnv.Reset:input_type -> battlesnake_env.ResetRequest
	4, // 3: battlesnake_env.BattlesnakeEnv.Step:input_type -> battlesnake_env.StepRequest
	6, // 4: battlesnake_env.BattlesnakeEnv.StepSignal:input_type -> battlesnake_env.StepSignalRequest
	1, // 5: battlesnake_env.BattlesnakeEnv.Configure:output_type -> battlesnake_env.ConfigResponse
	3, // 6: battlesnake_env.BattlesnakeEnv.Reset:output_type -> battlesnake_env.Observations
	5, // 7: battlesnake_env.BattlesnakeEnv.Step:output_type -> battlesnake_env.StepResponse
	7, // 8: battlesnake_env.BattlesnakeEnv.StepSignal:output_type -> battlesnake_env.StepSignalResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_battlesnake_env_proto_init() }
func file_battlesnake_env_proto_init() {
	if File_battlesnake_env_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_battlesnake_env_proto_rawDesc), len(file_battlesnake_env_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_battlesnake_env_proto_goTypes,
		DependencyIndexes: file_battlesnake_env_proto_depIdxs,
		MessageInfos:      file_battlesnake_env_proto_msgTypes,
	}.Build()
	File_battlesnake_env_proto = out.File
	file_battlesnake_env_proto_goTypes = nil
	file_battlesnake_env_proto_depIdxs = nil
}
